Desktop design for My Portfolio was completed
ometman/my-portfolio pull request #11
Opened 2023-01-20 18:08 UTC by ometman

I have completed the desktop design of the portfolio.

- The mobile version css and html files were refactored
- 2 css files were added for the desktop design 768px width and above
- New desktop background images were added for head and contact sections.
- This version was checked locally and was running well.
- Linters were checked locally and finally pushed.

2023-01-20 18:59 UTC, Zuhaib042 requested changes
Hi @ometman , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![close](https://media.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif)

## Highlights
✅ Descriptive PR
✅ Meaningful commit messages
✅ Professional Readme

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 18:59 UTC, Zuhaib042 commented on index.html
>                  <div class="card1 pos-1">
- [ ] Good job here but I am sorry to say that there are some slight issues that we need to work on to get it done.
kindly consider paying attention to the details of color, font-size, font-weight. we need to stick to the figma design as much as possible. following are some small issues that needs to be fixed in order to be similar to the figma design.
- [ ] The heading font is `40px` in figma design.
- [ ] The info under heading has different colors and font-weights in your design. kindly consider making them similar to the figma design.
- [ ] The technologies font-color is not similar to what's in the Fima design.
- [ ] And the button interactions don't have the specified color as in the figma design. In figma they have specified background and font colors of buttons in :hover and in :active states. kindly consider working on them to make them similar.
  -  kindly consider applying all these changes in all the cards.
![re](https://user-images.githubusercontent.com/96683843/213779324-27198377-b916-4cc6-b251-2038607cbd2e.jpg)

your design
![asd](https://user-images.githubusercontent.com/96683843/213779566-0ffa6fbc-452b-46bf-ab7a-3d912f8ad080.jpg)


figma design
![we](https://user-images.githubusercontent.com/96683843/213779477-5c9abb9d-a302-48f1-bd8b-c953d2c933fa.jpg)

2023-01-20 18:59 UTC, Zuhaib042 commented on css/stylesmin768.css
> +  }
- [ ] To stick with the figma design, we need to take to sub-containers in about me section. first section contains 40% of the width and the second section takes 60% of the width. and they both placed next to each other to be similar to the figma design.
- [ ] I will suggest applying the changes I described for the button interactions to all buttons in your design to have conformity in our design.
your design
![asdf](https://user-images.githubusercontent.com/96683843/213780503-de25024e-8c52-4438-8617-5711dd889f2b.jpg)

figma design
![qwe](https://user-images.githubusercontent.com/96683843/213780586-d3948419-a37f-41f7-9c49-54e77ecf1cc0.jpg)

2023-01-20 18:59 UTC, Zuhaib042 commented on css/styles.css
> +}
- [ ] There is some unwanted space above the navbar in the mobile design. I will suggest you fix that to make it aesthetically beautiful and perfect.
![as](https://user-images.githubusercontent.com/96683843/213782255-35ea5893-a316-47ed-b83f-c720ba89da54.jpg)

2023-01-20 18:59 UTC, Zuhaib042 commented on css/styles.css
> +}
- [ ] There is an unwanted `hr` element that is unnecessary for the design. I will highly recommend removing it to make it similar to the Figma design.
![sd](https://user-images.githubusercontent.com/96683843/213782722-ec7c6a24-75f6-4dbb-8faf-019c299ff97f.jpg)

2023-01-20 19:58 UTC, ometman commented on css/styles.css
> +}
Great review. The space above the top was in the figma design and suggested that the battery, time and network signal icons appear them. I guess it is not needed?

2023-01-20 19:59 UTC, ometman commented on css/stylesmin768.css
> +  }
Good observation. Thanks.

2023-01-20 20:00 UTC, ometman commented on index.html
>                  <div class="card1 pos-1">
You are right!

2023-01-21 21:56 UTC, ometman commented on css/styles.css
> +}
All the requested changes have been done.

2023-01-21 22:30 UTC, AbayomiOlaoye approved these changes
Hi @ometman 👏 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Great implementation of reviewer's suggestions :heavy_check_mark: 
- Good UI implementation :heavy_check_mark: 
- Linter checks are passing :heavy_check_mark: 
- Great attitude to feedback ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 22:30 UTC, AbayomiOlaoye commented on css/stylesmin768.css
> +    top: 1px;
- [ ] [OPTIONAL] You have a beautiful design here. Could you take a cursory look at the image below, did you see the blue background struggling to show after your header? I am not sure this is good for your design. One might think it's a mistake since whatever the user scrolled past is most likely not needed at the moment. I suggest you set your `top: 0` so that it can cover the space.

![image](https://user-images.githubusercontent.com/99715640/213889403-b122fc60-ce04-4372-9aba-a4c4ea33191f.png)

2023-01-21 22:33 UTC, merged