Implementation of Mobile Menu through Pair Programming
ometman/my-portfolio pull request #17
Opened 2023-01-31 02:30 UTC by ometman

- Index.html was modified to add mobile menu navigation 
- The CSS files were modified to style the mobile menu
- A Javascript file was added to support the opening of the menu 
- A close button was added to support the closing of the menu
- The menu items were linked appropriately to the various sections when clicked
-Javascript linters files were added to enable testing and validation of js code.
-The README.md was updated to reflect contributors, future features, and project information.
-The menu was tested and was working
-Linters were run and passed

2023-01-31 03:05 UTC, descholar-ceo requested changes
Hi @ometman 🤝 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not having all of the required linters, kindly install eslint as it's one of the core requirements, follow this [guide](https://github.com/microverseinc/linters-config/tree/master/javascript)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-31 03:33 UTC, ometman commented
Thank you. for the reminder. After passing locally, I didn't update the remote linters.yml.  It has been done now and validated.

2023-01-31 03:40 UTC, ometman commented
Hello @descholar-ceo,
I have done the linters update.  The dashboard has not been reset for the request for review.
I would like to inform you that if okay you can proceed with the review. Thanks again.

2023-01-31 04:48 UTC, t-yanick requested changes
Hi @ometman , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive PR
:heavy_check_mark: Great job adding the Eslint linters and all checks passing

There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 04:48 UTC, t-yanick commented on README.md
- [ ] Kindly give a more descriptive title to this Readme, rather than using Microverse Project. We are trying our possible best to personalize all Microverse projects

2023-01-31 04:48 UTC, t-yanick commented on README.md
>  - **Can I use this project?**
- [ ] Kindly add all the commands involved for someone to be able to run your project locally. These steps are missing in your ReadMe.

2023-01-31 04:48 UTC, t-yanick commented on index.html
> -                <!--use nav here later-->
- [ ] Please kindly ensure your `package.json` file is available in your repo. Without it `npm install` is impossible. I advise you clone your repo and try installing dependencies. Without it, running your project locally is an issue.

2023-01-31 05:01 UTC, ometman commented on README.md
Okay.  Thanks for the good explanation.

2023-01-31 05:03 UTC, ometman commented on index.html
> -                <!--use nav here later-->
Okay. Will work on it.

2023-01-31 05:26 UTC, ometman commented on README.md
>  - **Can I use this project?**
Thanks @t-yanick . I wish you would expatiate a little.  I indicated that but not under the section you quoted.

2023-01-31 18:24 UTC, ometman commented
All review feedback changes implemented.

2023-01-31 18:43 UTC, topeogunleye approved these changes
### Hi @ometman, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 05:26 UTC, ometman commented
Thank you. Proceeding with Portfolio Details Modals.

2023-02-01 05:27 UTC, merged