Aboutme section complete
ometman/My-portfolio pull request #4
Opened 2022-12-09 14:24 UTC by ometman

I have completed the about me section. Brief description about myself,  social media handles were added, languages, frameworks and skills were also added as links..

2022-12-09 18:13 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @ometman, :wave: 

Good Work So Far!!! :+1:  
You have implemented some required changes from the previous reviewer. There are still some issues you need to fix.

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
✔️ Linters checks are passing
✔️ Use GitHub Flow
✔️ Meaningful commit messages.

## Required Changes ♻️

_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 18:13 UTC, Tufahel commented on css/styles.css
> +  }
- [ ] As per the [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) there should be some extra `space` between the border and the `javascript`, `html` and `css` icon. Kindly fix this to match the design below.
  - ***Figma Design***
  ![Screenshot from 2022-12-10 00-00-02](https://user-images.githubusercontent.com/60083437/206764411-5db11b3d-890f-4f6c-b872-e803622ea5d7.png)
  - ***Your Design***
  ![Screenshot from 2022-12-10 00-01-13](https://user-images.githubusercontent.com/60083437/206764511-0ce91aa8-7893-4f7d-8198-a6de1a7fabc5.png)

2022-12-09 21:06 UTC, ometman commented on css/styles.css
> +  }
All the comments on the review have been observed for implementation.

2022-12-10 20:26 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @ometman, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 20:26 UTC, Qoosim commented on index.html
> +                </div>
- [ ] As mentioned by the previous reviewer, you're advised to stick to the figma design as close as possible. Kindly look into the background color of your design and that of the figma design. The background color of your design is a bit darker to what is on the figma design. Also left padding on the each container of the language has not been implemented. Kindly attend to that too.

### Your Design
![your-design](https://user-images.githubusercontent.com/26597432/206873880-7243d414-95be-43f0-9446-1192f97a687e.png)

### Figma Design
![figma-design](https://user-images.githubusercontent.com/26597432/206873943-73e5f59f-4886-435b-96ce-b8efc94ae1b8.png)

2022-12-10 22:56 UTC, ometman commented on index.html
> +                </div>
Effected alignment changes at skills section of about me section.  I used the original colors at found but the rendering seems a little different as per system. Thanks

2022-12-10 23:15 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @ometman, 

Your project is complete! Great job for following the project requirement🥇and implementing changes requested by the previous reviewers. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations! 🎉💯🌟 

<img src="https://camo.githubusercontent.com/4799731d86dd0d52a0bb7e22af48077bd16556ee26061146e987e9a98d36ee0d/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

- [ ] [OPTIONAL but recommended] I would kindly suggest you stick to the Figma template design as much as possible. I notice some light grey spaces outside your design responsiveness. which implies that your project is not fitting into the `375px` screen size as requested in the project requirement. Kindly find a way to fix that.

Your design 👇 

![omet](https://user-images.githubusercontent.com/78634841/206878948-0d425661-aeb1-4be8-8245-7c297568cf38.png)


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-11 04:29 UTC, merged

2023-01-12 17:50 UTC, GedeonTS reviewed
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @ometman ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- No linter errors :+1: 
- Good use of GitHub flow :+1: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._